
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 34;
  public static final int POW = 36;
  public static final int STRING_LITERAL = 64;
  public static final int LBRACKET = 57;
  public static final int INCREMENT = 37;
  public static final int CHAR = 29;
  public static final int CHAR_LITERAL = 63;
  public static final int GE = 45;
  public static final int FIND = 24;
  public static final int REMOVE = 20;
  public static final int XOR = 49;
  public static final int CASE = 6;
  public static final int DOUBLE = 27;
  public static final int LPAREN = 50;
  public static final int CONTINUE = 12;
  public static final int INT = 26;
  public static final int PRINTLN = 13;
  public static final int DECREMENT = 38;
  public static final int FOR = 9;
  public static final int MINUS = 32;
  public static final int RPAREN = 51;
  public static final int BOOLEAN_LITERAL = 62;
  public static final int SEMICOLON = 54;
  public static final int NOT = 48;
  public static final int AND = 46;
  public static final int LT = 42;
  public static final int APPEND = 19;
  public static final int OR = 47;
  public static final int COMMA = 56;
  public static final int BOOL = 28;
  public static final int PLUS = 31;
  public static final int MULTIPLY = 33;
  public static final int ASSIGN = 39;
  public static final int IF = 3;
  public static final int DOT = 59;
  public static final int LE = 44;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int RBRACKET = 58;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MODULO = 35;
  public static final int NEQ = 41;
  public static final int START = 16;
  public static final int BREAK = 11;
  public static final int TOSTRING = 23;
  public static final int VOID = 14;
  public static final int EQ = 40;
  public static final int SWITCH = 5;
  public static final int COLON = 55;
  public static final int LBRACE = 52;
  public static final int ELSE = 4;
  public static final int START_WITH = 25;
  public static final int WHILE = 8;
  public static final int LIST = 17;
  public static final int DEFAULT = 7;
  public static final int RBRACE = 53;
  public static final int STRING = 30;
  public static final int DOUBLE_LITERAL = 61;
  public static final int GT = 43;
  public static final int VAR = 2;
  public static final int LENGTH = 22;
  public static final int ROUND = 21;
  public static final int DO = 10;
  public static final int IDENTIFIER = 65;
  public static final int INTEGER_LITERAL = 60;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "WHILE",
  "FOR",
  "DO",
  "BREAK",
  "CONTINUE",
  "PRINTLN",
  "VOID",
  "RETURN",
  "START",
  "LIST",
  "NEW",
  "APPEND",
  "REMOVE",
  "ROUND",
  "LENGTH",
  "TOSTRING",
  "FIND",
  "START_WITH",
  "INT",
  "DOUBLE",
  "BOOL",
  "CHAR",
  "STRING",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "MODULO",
  "POW",
  "INCREMENT",
  "DECREMENT",
  "ASSIGN",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "LE",
  "GE",
  "AND",
  "OR",
  "NOT",
  "XOR",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "COLON",
  "COMMA",
  "LBRACKET",
  "RBRACKET",
  "DOT",
  "INTEGER_LITERAL",
  "DOUBLE_LITERAL",
  "BOOLEAN_LITERAL",
  "CHAR_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER"
  };
}

