// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/lexer/JavaUSAC.flex

package lexer;

import java_cup.runtime.*;
import parser.sym;
import reports.TablaErrores;
import reports.ErrorTipo;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\37\u0200\1\u0300\u10de\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\4\1\5\2\0\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\11\22"+
    "\1\23\1\24\1\25\1\26\1\27\2\0\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\41\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\3\41\1\56\1\57"+
    "\1\60\1\61\1\62\1\0\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\63\1\46\1\47\1\41\1\64\1\51\1\65"+
    "\1\53\1\54\1\55\3\41\1\66\1\67\1\70\262\0"+
    "\2\71\115\0\1\72\u01aa\0\1\73\325\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\2\15"+
    "\1\16\1\17\1\20\1\21\1\22\20\23\1\24\1\25"+
    "\1\26\1\27\1\1\1\30\2\1\1\31\1\0\1\32"+
    "\1\0\1\33\2\0\1\34\1\35\1\36\1\0\1\2"+
    "\1\0\1\37\1\40\1\41\7\23\1\42\4\23\1\0"+
    "\1\43\3\23\1\0\13\23\1\44\1\43\3\0\1\45"+
    "\1\0\1\46\4\23\1\0\5\23\1\0\2\23\1\47"+
    "\1\0\1\50\2\23\1\0\1\51\1\23\1\0\6\23"+
    "\1\0\1\23\1\0\1\23\1\52\1\23\1\0\1\23"+
    "\1\0\1\50\2\0\1\23\1\53\1\23\2\54\1\55"+
    "\3\23\2\56\1\0\2\57\1\23\2\60\1\23\1\0"+
    "\5\23\1\0\1\23\1\0\1\23\1\0\1\61\2\62"+
    "\1\23\2\0\1\23\2\63\1\23\1\0\2\23\1\61"+
    "\1\23\2\64\2\23\1\65\1\66\1\23\1\0\1\23"+
    "\1\0\1\23\1\0\2\67\1\66\1\70\1\23\1\0"+
    "\1\23\1\71\1\72\1\23\1\0\1\73\1\74\1\23"+
    "\2\75\2\76\1\23\2\0\1\23\1\0\1\77\2\64"+
    "\2\23\2\0\2\100\1\23\1\0\2\101\1\23\1\0"+
    "\2\102";

  private static int [] zzUnpackAction() {
    int [] result = new int[237];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\74\0\170\0\264\0\360\0\74\0\u012c"+
    "\0\u0168\0\74\0\74\0\u01a4\0\u01e0\0\74\0\u021c\0\74"+
    "\0\u0258\0\u0294\0\u02d0\0\74\0\74\0\u030c\0\u0348\0\u0384"+
    "\0\u03c0\0\u03fc\0\u0438\0\u0474\0\u04b0\0\u04ec\0\u0528\0\u0564"+
    "\0\u05a0\0\u05dc\0\u0618\0\u0654\0\u0690\0\u06cc\0\u0708\0\u0744"+
    "\0\74\0\74\0\74\0\74\0\u0780\0\74\0\u07bc\0\u07f8"+
    "\0\74\0\360\0\74\0\u0834\0\74\0\u0870\0\u08ac\0\74"+
    "\0\74\0\74\0\u08e8\0\u0924\0\u0960\0\74\0\74\0\74"+
    "\0\u099c\0\u09d8\0\u0a14\0\u0a50\0\u0a8c\0\u0ac8\0\u0b04\0\u0b40"+
    "\0\u0b7c\0\u0bb8\0\u0bf4\0\u0c30\0\u0c6c\0\u0528\0\u0ca8\0\u0ce4"+
    "\0\u0d20\0\u0d5c\0\u0d98\0\u0dd4\0\u0e10\0\u0e4c\0\u0e88\0\u0ec4"+
    "\0\u0f00\0\u0f3c\0\u0f78\0\u0fb4\0\u0ff0\0\74\0\74\0\u102c"+
    "\0\u1068\0\u10a4\0\74\0\u10e0\0\u0960\0\u111c\0\u1158\0\u1194"+
    "\0\u11d0\0\u120c\0\u1248\0\u1284\0\u12c0\0\u12fc\0\u1338\0\u1374"+
    "\0\u13b0\0\u13ec\0\u0528\0\u1428\0\u0528\0\u1464\0\u14a0\0\u14dc"+
    "\0\u0528\0\u1518\0\u1554\0\u1590\0\u15cc\0\u1608\0\u1644\0\u1680"+
    "\0\u16bc\0\u16f8\0\u1734\0\u1770\0\u17ac\0\u0528\0\u17e8\0\u1824"+
    "\0\u1860\0\u189c\0\74\0\u18d8\0\u1914\0\u1950\0\u0528\0\u198c"+
    "\0\u0528\0\74\0\u0528\0\u19c8\0\u1a04\0\u1a40\0\u0528\0\74"+
    "\0\u1a7c\0\u0528\0\74\0\u1ab8\0\u0528\0\74\0\u1af4\0\u1b30"+
    "\0\u1b6c\0\u1ba8\0\u1be4\0\u1c20\0\u1c5c\0\u1c98\0\u1cd4\0\u1d10"+
    "\0\u1d4c\0\u1d88\0\u0528\0\u0528\0\74\0\u1dc4\0\u1e00\0\u1e3c"+
    "\0\u1e78\0\u0528\0\74\0\u1eb4\0\u1ef0\0\u1f2c\0\u1f68\0\74"+
    "\0\u1fa4\0\u1fe0\0\u201c\0\u2058\0\u2094\0\u0528\0\u20d0\0\u210c"+
    "\0\u2148\0\u2184\0\u21c0\0\u21fc\0\u2238\0\u0528\0\74\0\u2274"+
    "\0\u0528\0\u22b0\0\u22ec\0\u2328\0\u0528\0\u0528\0\u2364\0\u23a0"+
    "\0\u0528\0\u0528\0\u23dc\0\u0528\0\74\0\u0528\0\74\0\u2418"+
    "\0\u2454\0\u2490\0\u24cc\0\u2508\0\u0528\0\u0528\0\74\0\u2544"+
    "\0\u2580\0\u25bc\0\u25f8\0\u0528\0\74\0\u2634\0\u2670\0\u0528"+
    "\0\74\0\u26ac\0\u26e8\0\u0528\0\74";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[237];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\2\37\1\40\2\37"+
    "\1\41\1\37\1\42\1\37\1\43\1\44\1\45\1\46"+
    "\1\37\1\47\1\50\1\51\1\2\1\52\1\53\1\37"+
    "\1\42\1\44\1\46\1\54\1\55\1\56\1\57\1\60"+
    "\1\2\76\0\1\3\117\0\1\61\45\0\5\62\1\63"+
    "\51\62\1\64\14\62\7\0\1\65\64\0\10\66\1\0"+
    "\46\66\1\67\14\66\13\0\1\70\74\0\1\71\75\0"+
    "\1\72\70\0\1\73\4\0\1\74\72\0\1\75\73\0"+
    "\1\75\1\0\2\23\77\0\1\76\73\0\1\77\73\0"+
    "\1\100\66\0\2\37\5\0\17\37\1\101\6\37\4\0"+
    "\4\37\27\0\2\37\5\0\16\37\1\102\1\37\1\103"+
    "\5\37\4\0\2\37\1\103\1\37\27\0\2\37\5\0"+
    "\1\104\6\37\1\105\6\37\1\106\7\37\4\0\4\37"+
    "\27\0\2\37\5\0\4\37\1\107\11\37\1\110\7\37"+
    "\4\0\4\37\27\0\2\37\5\0\13\37\1\111\12\37"+
    "\4\0\4\37\27\0\2\37\5\0\1\112\7\37\1\113"+
    "\5\37\1\114\7\37\4\0\4\37\3\0\1\115\23\0"+
    "\2\37\5\0\26\37\4\0\4\37\27\0\2\37\5\0"+
    "\5\37\1\116\7\37\1\117\10\37\4\0\1\37\1\117"+
    "\2\37\27\0\2\37\5\0\4\37\1\120\3\37\1\121"+
    "\15\37\4\0\4\37\3\0\1\122\23\0\2\37\5\0"+
    "\4\37\1\123\21\37\4\0\4\37\27\0\2\37\5\0"+
    "\20\37\1\124\5\37\4\0\2\37\1\124\1\37\27\0"+
    "\2\37\5\0\4\37\1\125\11\37\1\126\7\37\4\0"+
    "\4\37\27\0\2\37\5\0\22\37\1\127\2\37\1\130"+
    "\4\0\3\37\1\127\27\0\2\37\5\0\16\37\1\131"+
    "\1\37\1\132\5\37\4\0\2\37\1\132\1\37\27\0"+
    "\2\37\5\0\1\133\15\37\1\134\7\37\4\0\4\37"+
    "\27\0\2\37\5\0\7\37\1\135\16\37\4\0\4\37"+
    "\75\0\1\136\41\0\1\137\7\0\1\140\15\0\1\140"+
    "\62\0\1\141\2\0\1\142\7\0\1\141\13\0\1\62"+
    "\2\0\1\62\46\0\1\62\3\0\3\62\16\0\1\143"+
    "\70\0\1\66\2\0\1\66\46\0\1\66\3\0\3\66"+
    "\6\0\13\73\1\144\60\73\2\74\2\0\70\74\21\0"+
    "\2\145\72\0\2\37\5\0\17\37\1\146\6\37\4\0"+
    "\4\37\27\0\2\37\5\0\16\37\1\147\7\37\4\0"+
    "\4\37\27\0\2\37\5\0\4\37\1\150\21\37\4\0"+
    "\4\37\27\0\2\37\5\0\21\37\1\151\4\37\4\0"+
    "\4\37\4\0\1\152\22\0\2\37\5\0\1\153\25\37"+
    "\4\0\4\37\27\0\2\37\5\0\15\37\1\154\10\37"+
    "\4\0\1\37\1\154\2\37\27\0\2\37\5\0\5\37"+
    "\1\155\20\37\4\0\4\37\27\0\2\37\5\0\23\37"+
    "\1\156\2\37\4\0\4\37\27\0\2\37\5\0\21\37"+
    "\1\157\4\37\4\0\4\37\4\0\1\160\22\0\2\37"+
    "\5\0\13\37\1\161\12\37\4\0\4\37\27\0\2\37"+
    "\5\0\15\37\1\162\10\37\4\0\1\37\1\162\2\37"+
    "\27\0\2\37\5\0\20\37\1\163\5\37\4\0\2\37"+
    "\1\163\1\37\53\0\1\164\15\0\1\164\31\0\2\37"+
    "\5\0\22\37\1\165\3\37\4\0\3\37\1\165\27\0"+
    "\2\37\5\0\15\37\1\166\10\37\4\0\1\37\1\166"+
    "\2\37\27\0\2\37\5\0\21\37\1\167\4\37\4\0"+
    "\4\37\4\0\1\170\52\0\1\170\20\0\1\170\22\0"+
    "\2\37\5\0\25\37\1\171\4\0\4\37\27\0\2\37"+
    "\5\0\10\37\1\172\15\37\4\0\4\37\3\0\1\173"+
    "\23\0\2\37\5\0\14\37\1\174\5\37\1\175\3\37"+
    "\4\0\3\37\1\175\27\0\2\37\5\0\23\37\1\176"+
    "\2\37\4\0\4\37\27\0\2\37\5\0\1\177\17\37"+
    "\1\200\5\37\4\0\2\37\1\200\1\37\27\0\2\37"+
    "\5\0\10\37\1\201\15\37\4\0\4\37\3\0\1\202"+
    "\23\0\2\37\5\0\21\37\1\203\4\37\4\0\4\37"+
    "\4\0\1\204\22\0\2\37\5\0\23\37\1\205\2\37"+
    "\4\0\4\37\27\0\2\37\5\0\20\37\1\206\5\37"+
    "\4\0\2\37\1\206\1\37\27\0\2\37\5\0\10\37"+
    "\1\207\15\37\4\0\4\37\3\0\1\210\23\0\2\37"+
    "\5\0\10\37\1\211\15\37\4\0\4\37\3\0\1\212"+
    "\54\0\1\213\12\0\1\213\36\0\1\214\17\0\1\215"+
    "\13\0\1\215\47\0\1\202\30\0\1\202\2\0\13\73"+
    "\1\144\4\73\1\3\53\73\21\0\2\37\5\0\4\37"+
    "\1\216\21\37\4\0\4\37\27\0\2\37\5\0\13\37"+
    "\1\217\12\37\4\0\4\37\27\0\2\37\5\0\1\220"+
    "\25\37\4\0\4\37\27\0\2\37\5\0\4\37\1\221"+
    "\21\37\4\0\4\37\42\0\1\222\60\0\2\37\5\0"+
    "\20\37\1\223\5\37\4\0\2\37\1\223\1\37\27\0"+
    "\2\37\5\0\22\37\1\224\3\37\4\0\3\37\1\224"+
    "\27\0\2\37\5\0\1\225\25\37\4\0\4\37\27\0"+
    "\2\37\5\0\1\37\1\226\24\37\4\0\4\37\27\0"+
    "\2\37\5\0\4\37\1\227\21\37\4\0\4\37\42\0"+
    "\1\230\60\0\2\37\5\0\21\37\1\205\4\37\4\0"+
    "\4\37\4\0\1\231\22\0\2\37\5\0\3\37\1\232"+
    "\22\37\4\0\4\37\41\0\1\233\61\0\2\37\5\0"+
    "\6\37\1\234\17\37\4\0\4\37\27\0\2\37\5\0"+
    "\22\37\1\235\3\37\4\0\3\37\1\235\60\0\1\236"+
    "\12\0\1\236\27\0\2\37\5\0\15\37\1\237\10\37"+
    "\4\0\1\37\1\237\2\37\53\0\1\240\15\0\1\240"+
    "\31\0\2\37\5\0\16\37\1\241\7\37\4\0\4\37"+
    "\27\0\2\37\5\0\23\37\1\242\2\37\4\0\4\37"+
    "\27\0\2\37\5\0\15\37\1\243\10\37\4\0\1\37"+
    "\1\243\2\37\27\0\2\37\5\0\20\37\1\244\5\37"+
    "\4\0\2\37\1\244\1\37\27\0\2\37\5\0\10\37"+
    "\1\245\15\37\4\0\4\37\3\0\1\246\23\0\2\37"+
    "\5\0\22\37\1\247\3\37\4\0\3\37\1\247\60\0"+
    "\1\250\12\0\1\250\27\0\2\37\5\0\22\37\1\251"+
    "\3\37\4\0\3\37\1\251\60\0\1\252\12\0\1\252"+
    "\27\0\2\37\5\0\4\37\1\253\21\37\4\0\4\37"+
    "\27\0\2\37\5\0\3\37\1\254\22\37\4\0\4\37"+
    "\41\0\1\255\61\0\2\37\5\0\13\37\1\256\12\37"+
    "\4\0\4\37\51\0\1\257\100\0\1\260\13\0\1\260"+
    "\47\0\1\246\30\0\1\246\23\0\2\37\5\0\15\37"+
    "\1\261\10\37\4\0\1\37\1\261\2\37\27\0\2\37"+
    "\5\0\12\37\1\262\13\37\4\0\4\37\5\0\1\263"+
    "\21\0\2\37\5\0\10\37\1\264\15\37\4\0\4\37"+
    "\3\0\1\265\23\0\2\37\5\0\23\37\1\266\2\37"+
    "\4\0\4\37\27\0\2\37\5\0\13\37\1\267\12\37"+
    "\4\0\4\37\42\0\1\270\60\0\2\37\5\0\22\37"+
    "\1\271\3\37\4\0\3\37\1\271\27\0\2\37\5\0"+
    "\22\37\1\272\3\37\4\0\3\37\1\272\60\0\1\273"+
    "\12\0\1\273\27\0\2\37\5\0\24\37\1\274\1\37"+
    "\4\0\4\37\27\0\2\37\5\0\20\37\1\275\5\37"+
    "\4\0\2\37\1\275\1\37\27\0\2\37\5\0\3\37"+
    "\1\276\22\37\4\0\4\37\27\0\2\37\5\0\22\37"+
    "\1\277\3\37\4\0\3\37\1\277\27\0\2\37\5\0"+
    "\15\37\1\300\10\37\4\0\1\37\1\300\2\37\53\0"+
    "\1\301\15\0\1\301\31\0\2\37\5\0\2\37\1\302"+
    "\23\37\4\0\4\37\40\0\1\303\62\0\2\37\5\0"+
    "\20\37\1\304\5\37\4\0\2\37\1\304\1\37\56\0"+
    "\1\305\13\0\1\305\30\0\2\37\5\0\4\37\1\306"+
    "\21\37\4\0\4\37\42\0\1\307\111\0\1\310\12\0"+
    "\1\310\27\0\2\37\5\0\3\37\1\311\22\37\4\0"+
    "\4\37\27\0\2\37\5\0\15\37\1\312\10\37\4\0"+
    "\1\37\1\312\2\37\53\0\1\313\15\0\1\313\31\0"+
    "\2\37\5\0\13\37\1\314\12\37\4\0\4\37\27\0"+
    "\2\37\5\0\4\37\1\315\21\37\4\0\4\37\27\0"+
    "\2\37\5\0\7\37\1\316\16\37\4\0\4\37\27\0"+
    "\2\37\5\0\13\37\1\317\12\37\4\0\4\37\51\0"+
    "\1\320\51\0\2\37\5\0\4\37\1\321\21\37\4\0"+
    "\4\37\27\0\2\37\5\0\15\37\1\322\10\37\4\0"+
    "\1\37\1\322\2\37\27\0\2\37\5\0\26\37\4\0"+
    "\1\323\3\37\27\0\2\37\5\0\6\37\1\324\17\37"+
    "\4\0\4\37\44\0\1\325\56\0\2\37\5\0\7\37"+
    "\1\326\16\37\4\0\4\37\45\0\1\327\55\0\2\37"+
    "\5\0\10\37\1\330\15\37\4\0\4\37\3\0\1\331"+
    "\42\0\1\331\30\0\1\331\64\0\1\332\32\0\2\37"+
    "\5\0\23\37\1\333\2\37\4\0\4\37\61\0\1\334"+
    "\41\0\2\37\5\0\22\37\1\335\3\37\4\0\3\37"+
    "\1\335\27\0\2\37\5\0\15\37\1\336\10\37\4\0"+
    "\1\37\1\336\2\37\53\0\1\337\15\0\1\337\31\0"+
    "\2\37\5\0\25\37\1\340\4\0\4\37\27\0\2\37"+
    "\5\0\15\37\1\341\10\37\4\0\1\37\1\341\2\37"+
    "\53\0\1\342\15\0\1\342\65\0\1\343\37\0\2\37"+
    "\5\0\4\37\1\344\21\37\4\0\4\37\42\0\1\345"+
    "\60\0\2\37\5\0\10\37\1\346\15\37\4\0\4\37"+
    "\3\0\1\347\23\0\2\37\5\0\6\37\1\350\17\37"+
    "\4\0\4\37\44\0\1\351\75\0\1\347\30\0\1\347"+
    "\23\0\2\37\5\0\22\37\1\352\3\37\4\0\3\37"+
    "\1\352\60\0\1\353\12\0\1\353\27\0\2\37\5\0"+
    "\7\37\1\354\16\37\4\0\4\37\45\0\1\355\34\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[10020];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\2\1\2\11\2\1\1\11"+
    "\1\1\1\11\3\1\2\11\23\1\4\11\1\1\1\11"+
    "\2\1\1\11\1\0\1\11\1\0\1\11\2\0\3\11"+
    "\1\0\1\1\1\0\3\11\14\1\1\0\4\1\1\0"+
    "\13\1\2\11\3\0\1\11\1\0\5\1\1\0\5\1"+
    "\1\0\3\1\1\0\3\1\1\0\2\1\1\0\6\1"+
    "\1\0\1\1\1\0\3\1\1\0\1\1\1\0\1\11"+
    "\2\0\4\1\1\11\5\1\1\11\1\0\1\1\1\11"+
    "\2\1\1\11\1\1\1\0\5\1\1\0\1\1\1\0"+
    "\1\1\1\0\2\1\1\11\1\1\2\0\2\1\1\11"+
    "\1\1\1\0\2\1\1\11\10\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\11\3\1\1\0\4\1\1\0"+
    "\4\1\1\11\1\1\1\11\1\1\2\0\1\1\1\0"+
    "\2\1\1\11\2\1\2\0\1\1\1\11\1\1\1\0"+
    "\1\1\1\11\1\1\1\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[237];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // ---- Soporte de errores léxicos persistente (NO se pierde al regenerar) ----
    private TablaErrores tablaErrores;

    public void setTablaErrores(TablaErrores tablaErrores) {
        this.tablaErrores = tablaErrores;
    }

    private void agregarErrorLexico(String caracter, int linea, int columna) {
        String desc = String.format("Símbolo no reconocido: '%s'", caracter);
        if (tablaErrores != null) {
            tablaErrores.agregarError(ErrorTipo.LEXICO, desc, linea, columna);
        } else {
            System.err.println("Error léxico: " + desc + " en línea " + linea + ", columna " + columna);
        }
    }

    private void agregarErrorLexicoDesc(String desc, int linea, int columna) {
        if (tablaErrores != null) {
            tablaErrores.agregarError(ErrorTipo.LEXICO, desc, linea, columna);
        } else {
            System.err.println("Error léxico: " + desc + " en línea " + linea + ", columna " + columna);
        }
    }

    private Symbol symbol(int type, int line, int column) {
        return new Symbol(type, line, column);
    }

    private Symbol symbol(int type, Object value, int line, int column) {
        return new Symbol(type, line, column, value);
    }

    private Symbol symbol(int type) {
        return symbol(type, yyline + 1, yycolumn + 1);
    }

    private Symbol symbol(int type, Object value) {
        return symbol(type, value, yyline + 1, yycolumn + 1);
    }

    // Helper method to unescape strings
    private String unescape(String s) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '\\') {
                i++;
                if (i < s.length()) {
                    char next = s.charAt(i);
                    switch (next) {
                        case 'n': sb.append('\n'); break;
                        case 'r': sb.append('\r'); break;
                        case 't': sb.append('\t'); break;
                        case '\\': sb.append('\\'); break;
                        case '\"': sb.append('\"'); break;
                        case '\'': sb.append('\''); break;
                        default: sb.append(next); break;
                    }
                } else {
                    sb.append(c);
                }
            } else {
                sb.append(c);
            }
        }
        return sb.toString();
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { agregarErrorLexico(yytext(), yyline+1, yycolumn+1);
                                    return symbol(sym.error);
            }
          // fall through
          case 67: break;
          case 2:
            { /* ignore */
            }
          // fall through
          case 68: break;
          case 3:
            { return symbol(sym.NOT);
            }
          // fall through
          case 69: break;
          case 4:
            { return symbol(sym.MODULO);
            }
          // fall through
          case 70: break;
          case 5:
            { return symbol(sym.LPAREN);
            }
          // fall through
          case 71: break;
          case 6:
            { return symbol(sym.RPAREN);
            }
          // fall through
          case 72: break;
          case 7:
            { return symbol(sym.MULTIPLY);
            }
          // fall through
          case 73: break;
          case 8:
            { return symbol(sym.PLUS);
            }
          // fall through
          case 74: break;
          case 9:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 75: break;
          case 10:
            { return symbol(sym.MINUS);
            }
          // fall through
          case 76: break;
          case 11:
            { return symbol(sym.DOT);
            }
          // fall through
          case 77: break;
          case 12:
            { return symbol(sym.DIVIDE);
            }
          // fall through
          case 78: break;
          case 13:
            { return symbol(sym.INTEGER_LITERAL, Integer.parseInt(yytext()));
            }
          // fall through
          case 79: break;
          case 14:
            { return symbol(sym.COLON);
            }
          // fall through
          case 80: break;
          case 15:
            { return symbol(sym.SEMICOLON);
            }
          // fall through
          case 81: break;
          case 16:
            { return symbol(sym.LT);
            }
          // fall through
          case 82: break;
          case 17:
            { return symbol(sym.ASSIGN);
            }
          // fall through
          case 83: break;
          case 18:
            { return symbol(sym.GT);
            }
          // fall through
          case 84: break;
          case 19:
            { return symbol(sym.IDENTIFIER, yytext());
            }
          // fall through
          case 85: break;
          case 20:
            { return symbol(sym.LBRACKET);
            }
          // fall through
          case 86: break;
          case 21:
            { return symbol(sym.RBRACKET);
            }
          // fall through
          case 87: break;
          case 22:
            { return symbol(sym.XOR);
            }
          // fall through
          case 88: break;
          case 23:
            { return symbol(sym.LBRACE);
            }
          // fall through
          case 89: break;
          case 24:
            { return symbol(sym.RBRACE);
            }
          // fall through
          case 90: break;
          case 25:
            { return symbol(sym.NEQ);
            }
          // fall through
          case 91: break;
          case 26:
            { String text = yytext();
                                    text = text.substring(1, text.length()-1);
                                    text = unescape(text);
                                    return symbol(sym.STRING_LITERAL, text);
            }
          // fall through
          case 92: break;
          case 27:
            { return symbol(sym.AND);
            }
          // fall through
          case 93: break;
          case 28:
            { return symbol(sym.POW);
            }
          // fall through
          case 94: break;
          case 29:
            { return symbol(sym.INCREMENT);
            }
          // fall through
          case 95: break;
          case 30:
            { return symbol(sym.DECREMENT);
            }
          // fall through
          case 96: break;
          case 31:
            { return symbol(sym.LE);
            }
          // fall through
          case 97: break;
          case 32:
            { return symbol(sym.EQ);
            }
          // fall through
          case 98: break;
          case 33:
            { return symbol(sym.GE);
            }
          // fall through
          case 99: break;
          case 34:
            { return symbol(sym.DO);
            }
          // fall through
          case 100: break;
          case 35:
            { return symbol(sym.IF);
            }
          // fall through
          case 101: break;
          case 36:
            { return symbol(sym.OR);
            }
          // fall through
          case 102: break;
          case 37:
            { String text = yytext();
                                    text = text.substring(1, text.length()-1);
                                    text = unescape(text);
                                    if (text.length() == 1) {
                                        return symbol(sym.CHAR_LITERAL, text.charAt(0));
                                    } else {
                                        // Esto en práctica no debería ocurrir con esta regex, pero lo dejamos por robustez
                                        agregarErrorLexicoDesc("Char literal con más de un carácter", yyline+1, yycolumn+1);
                                        return symbol(sym.error);
                                    }
            }
          // fall through
          case 103: break;
          case 38:
            { return symbol(sym.DOUBLE_LITERAL, Double.parseDouble(yytext()));
            }
          // fall through
          case 104: break;
          case 39:
            { return symbol(sym.FOR);
            }
          // fall through
          case 105: break;
          case 40:
            { return symbol(sym.INT);
            }
          // fall through
          case 106: break;
          case 41:
            { return symbol(sym.NEW);
            }
          // fall through
          case 107: break;
          case 42:
            { return symbol(sym.VAR);
            }
          // fall through
          case 108: break;
          case 43:
            { return symbol(sym.BOOL);
            }
          // fall through
          case 109: break;
          case 44:
            { return symbol(sym.CASE);
            }
          // fall through
          case 110: break;
          case 45:
            { return symbol(sym.CHAR);
            }
          // fall through
          case 111: break;
          case 46:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 112: break;
          case 47:
            { return symbol(sym.FIND);
            }
          // fall through
          case 113: break;
          case 48:
            { return symbol(sym.LIST);
            }
          // fall through
          case 114: break;
          case 49:
            { return symbol(sym.BOOLEAN_LITERAL, Boolean.valueOf(yytext().equalsIgnoreCase("true")));
            }
          // fall through
          case 115: break;
          case 50:
            { return symbol(sym.VOID);
            }
          // fall through
          case 116: break;
          case 51:
            { return symbol(sym.BREAK);
            }
          // fall through
          case 117: break;
          case 52:
            { return symbol(sym.PRINTLN);
            }
          // fall through
          case 118: break;
          case 53:
            { return symbol(sym.ROUND);
            }
          // fall through
          case 119: break;
          case 54:
            { return symbol(sym.START);
            }
          // fall through
          case 120: break;
          case 55:
            { return symbol(sym.WHILE);
            }
          // fall through
          case 121: break;
          case 56:
            { return symbol(sym.APPEND);
            }
          // fall through
          case 122: break;
          case 57:
            { return symbol(sym.DOUBLE);
            }
          // fall through
          case 123: break;
          case 58:
            { return symbol(sym.LENGTH);
            }
          // fall through
          case 124: break;
          case 59:
            { return symbol(sym.REMOVE);
            }
          // fall through
          case 125: break;
          case 60:
            { return symbol(sym.RETURN);
            }
          // fall through
          case 126: break;
          case 61:
            { return symbol(sym.STRING);
            }
          // fall through
          case 127: break;
          case 62:
            { return symbol(sym.SWITCH);
            }
          // fall through
          case 128: break;
          case 63:
            { return symbol(sym.DEFAULT);
            }
          // fall through
          case 129: break;
          case 64:
            { return symbol(sym.CONTINUE);
            }
          // fall through
          case 130: break;
          case 65:
            { return symbol(sym.TOSTRING);
            }
          // fall through
          case 131: break;
          case 66:
            { return symbol(sym.START_WITH);
            }
          // fall through
          case 132: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
